version: '3.8'

services:
  product-service:
    build: ./product
    volumes:
      - ./product:/usr/src/app
    ports:
      - 5007:81

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5008:80
    depends_on:
      - product-service
